# Generated by Django 3.1.7 on 2021-02-21 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 17, 44, 56, 201716)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generate_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 17, 44, 56, 201716)),
        ),
    ]
