# Generated by Django 3.1.7 on 2021-02-21 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210221_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='status',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 34, 55, 554341)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generate_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 22, 34, 55, 554341)),
        ),
    ]
